sudo: false
before_script:
  - ./bin/install_deps
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS galette_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database galette_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -d galette_tests -a -f galette/install/scripts/pgsql.sql -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS galette_tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'use galette_tests; source galette/install/scripts/mysql.sql;'; fi"
  - wget https://github.com/atoum/atoum/releases/download/2.8.2/atoum.phar
script: php atoum.phar -mcn 1 -bf tests/TestsBootstrap.php -d tests/Galette/
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  - DB=pgsql
  - DB=mysql
notifications:
  irc:
    channels:
      - "irc.oftc.net#galette"
    template:
      - "%{build_number} by %{author} on %{branch}: %{message} "
      - "Build details: %{build_url}"
    use_notice: true
